### ISSUE TITLE
Error when running the frontend

### ISSUE THREAD

**Issue by beeman** [beeman/solana-dapp-anchor-v030#1]
This is an early attempt at making `create-solana-dapp` work with Anchor v0.30.0.

This repo is based on the latest `create-solana-dapp` and I made a few commits to make the `anchor` library work. 

`pnpm anchor build` and `pnpm anchor test` work.

However, the frontend does not seem to be happy.

![image](https://github.com/beeman/solana-dapp-anchor-v030/assets/36491/c47c5fac-b31e-4987-b964-c8535abf891d)

There's a bounty for the person who fixes this.

**Comment by Shiva953** [comment]
`App1713693601IDL` should be of `Idl` Type.
Working on the fix


Edit - Made a PR with the fix.

**Comment by Emma66886** [comment]
@beeman Good day, i already made a working update to this,
Kindly [click here to check the pull request](https://github.com/beeman/solana-dapp-anchor-v030/pull/4)
